name: First CI Demo

on:
  push:
  workflow_dispatch:

jobs:
  test-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: List files
        run: ls -la

      - name: Print success message
        run: echo "CI is working"
